version: '3.8'

services:

  db:
    image: postgres:15.4-alpine
    container_name: db
    # Внешние тома(volume) и место где они будут подключены внутри контейнера
    volumes:
      - postgres_db_dumps:/code/dumps
      - postgres_db_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env

  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: noemail@noemail.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   restart: always
  #   ports:
  #     - '8050:80'

  web:
    # Билд образа для запуска Django в разработке
    hostname: django-web
    container_name: django-web
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    # command: python ./app/manage.py runserver 0.0.0.0:8000
    # command: gunicorn ./app/django_conf.wsgi:application --bind 0.0.0.0:8000
    command: sh -c "./app/run.dev.sh"
    # Открываем порт 8000 внутри и снаружи
    ports:
      - 8000:8000
    # Открываем порт 8000 только внутри докера
    # expose:
    #   - 8000
    # Подключаем статические и медиа файлы
    # volumes:
    #   - static_volume:/djangoapp/app/static
    #   - media_volume:/djangoapp/app/media
    env_file:
      - .env
    depends_on:
      - db
  # nginx:
  #   image: nginx:alpine
  #   hostname: nginx
  #   container_name: nginx
  #   restart: always
  #   ports:
  #     - '8080:80'
  #     - '8443:443'
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - static_volume:/opt/web/static
  #     - media_volume:/opt/web/media
  #   depends_on:
  #     - web

volumes:
  postgres_db_dumps:
  postgres_db_data:
    # static_volume:
    # media_volume:
