version: '3.8'

services:

  # db:
  #   image: postgres:15.4-alpine
  #   container_name: db
  #   env_file:
  #     - .env
  #   # Внешние тома(volume) и место где они будут подключены внутри контейнера
  #   volumes:
  #     - postgres_db_dumps:/code/dumps
  #     - postgres_db_data:/var/lib/postgresql/data
  #   restart: always
  #   ports:
  #     - "${POSTGRES_PORT}:5432"

  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: noemail@noemail.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   restart: always
  #   ports:
  #     - '8050:80'

  web:
    # Билд образа для запуска Django в продакшене
    hostname: django-web
    container_name: django-web
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    # command: python ./app/manage.py runserver 0.0.0.0:8000
    # command: gunicorn ./app/django_conf.wsgi:application --bind 0.0.0.0:8000
    command: sh -c "./app/run.sh"
    # Открываем порт 8000 внутри и снаружи
    ports:
      - 8000:8000
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    hostname: nginx
    container_name: nginx
    restart: always
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

volumes:
  postgres_db_dumps:
  postgres_db_data:
