# Generated by Django 4.2.5 on 2023-10-11 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 13, 17, 52, 40, 409022, tzinfo=datetime.timezone.utc)),
        ),
    ]
