# Generated by Django 4.2.5 on 2023-10-13 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_studentuser_activation_key_expires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='password_hash',
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 15, 18, 55, 58, 844901, tzinfo=datetime.timezone.utc)),
        ),
    ]
