# Generated by Django 4.2.5 on 2023-10-14 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_remove_studentuser_password_hash_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='studentuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 21, 8, 41, 111089, tzinfo=datetime.timezone.utc)),
        ),
    ]
