# Generated by Django 4.2.5 on 2023-10-14 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_alter_studentuser_activation_key_expires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 21, 18, 18, 947730, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
    ]
