# Generated by Django 4.2.5 on 2023-10-15 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_alter_studentuser_activation_key_expires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 8, 41, 34, 759952, tzinfo=datetime.timezone.utc)),
        ),
    ]
