# Generated by Django 4.2.5 on 2023-10-15 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_alter_studentuser_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 17, 18, 4, 53, 95040, tzinfo=datetime.timezone.utc)),
        ),
    ]
