# Generated by Django 4.2.5 on 2023-10-19 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_alter_studentuser_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 21, 12, 26, 2, 134478, tzinfo=datetime.timezone.utc)),
        ),
    ]
