# Generated by Django 4.2.5 on 2023-10-22 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_alter_studentuser_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 16, 16, 57, 356478, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
    ]
