# Generated by Django 4.2.5 on 2023-10-22 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0015_alter_studentuser_activation_key_expires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 19, 0, 21, 379812, tzinfo=datetime.timezone.utc)),
        ),
    ]
