# Generated by Django 4.2.5 on 2023-10-23 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0017_alter_studentuser_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 25, 11, 10, 21, 600051, tzinfo=datetime.timezone.utc)),
        ),
    ]
