# Generated by Django 4.2.5 on 2023-10-26 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0017_alter_studentuser_activation_key_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='is_subscribed',
            field=models.BooleanField(default=False, verbose_name='Подписан на новости'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 28, 15, 8, 14, 252367, tzinfo=datetime.timezone.utc)),
        ),
    ]
