# Generated by Django 4.2.5 on 2023-10-27 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0018_studentuser_is_subscribed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 29, 9, 35, 28, 939777, tzinfo=datetime.timezone.utc)),
        ),
    ]
