# Generated by Django 4.2.5 on 2023-10-28 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0018_alter_studentuser_activation_key_expires'),
        ('authapp', '0022_alter_studentuser_activation_key_expires'),
    ]

    operations = [
    ]
