# Generated by Django 4.2.5 on 2023-10-28 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0023_merge_20231028_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 30, 18, 13, 15, 756828, tzinfo=datetime.timezone.utc)),
        ),
    ]
