# Generated by Django 4.2.5 on 2023-10-28 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0024_alter_studentuser_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 30, 19, 51, 13, 860455, tzinfo=datetime.timezone.utc)),
        ),
    ]
