# Generated by Django 4.2.5 on 2023-10-29 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0028_alter_studentuser_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 10, 58, 52, 525676, tzinfo=datetime.timezone.utc)),
        ),
    ]
