# Generated by Django 4.2.5 on 2023-10-29 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0030_alter_studentuser_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 14, 57, 54, 375540, tzinfo=datetime.timezone.utc)),
        ),
    ]
