# Generated by Django 4.2.5 on 2023-10-29 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0036_alter_studentuser_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 18, 0, 25, 472261, tzinfo=datetime.timezone.utc)),
        ),
    ]
