# Generated by Django 4.2.5 on 2023-10-29 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0037_alter_studentuser_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 18, 5, 50, 648391, tzinfo=datetime.timezone.utc)),
        ),
    ]
