# Generated by Django 4.2.5 on 2023-10-29 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0038_alter_studentuser_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 20, 44, 10, 257814, tzinfo=datetime.timezone.utc)),
        ),
    ]
