# Generated by Django 4.2.5 on 2023-10-29 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0039_alter_studentuser_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 22, 24, 9, 840776, tzinfo=datetime.timezone.utc)),
        ),
    ]
