# Generated by Django 4.2.5 on 2023-11-02 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0049_studentuser_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 19, 24, 53, 200536, tzinfo=datetime.timezone.utc)),
        ),
    ]
