# Generated by Django 4.2.5 on 2023-11-02 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0051_alter_studentuser_activation_key_expires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 19, 45, 18, 550992, tzinfo=datetime.timezone.utc)),
        ),
    ]
