# Generated by Django 4.2.5 on 2023-11-05 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0059_alter_studentuser_activation_key_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 7, 8, 31, 52, 471634, tzinfo=datetime.timezone.utc)),
        ),
    ]
