# Generated by Django 4.2.5 on 2023-11-05 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0060_studentuser_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 7, 8, 57, 49, 284072, tzinfo=datetime.timezone.utc)),
        ),
    ]
