# Generated by Django 4.2.5 on 2023-11-08 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0065_alter_studentuser_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 10, 15, 49, 0, 812954, tzinfo=datetime.timezone.utc)),
        ),
    ]
