# Generated by Django 4.2.5 on 2023-11-09 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0068_alter_studentuser_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 12, 11, 0, 208289, tzinfo=datetime.timezone.utc)),
        ),
    ]
