# Generated by Django 4.2.5 on 2023-11-10 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0070_alter_studentuser_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 12, 9, 50, 11, 239596, tzinfo=datetime.timezone.utc)),
        ),
    ]
