# Generated by Django 4.2.5 on 2023-11-19 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0074_alter_studentuser_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 21, 13, 29, 47, 530692, tzinfo=datetime.timezone.utc)),
        ),
    ]
