# Generated by Django 4.2.5 on 2023-10-11 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='Преимущество')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удален')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='Польза')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удален')),
            ],
            options={
                'verbose_name': 'Польза',
                'verbose_name_plural': 'Польза',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='Название курса')),
                ('description', models.TextField(blank=True, verbose_name='Описание курса')),
                ('price', models.FloatField(verbose_name='Стоимость курса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('teaser_video', models.FilePathField(blank=True, null=True, verbose_name='Тизер-видео')),
                ('category', models.CharField(choices=[('ART', 'искусство'), ('DESIGN', 'дизайн'), ('SOFT_SKILLS', 'soft skills')], max_length=11, verbose_name='Категория курса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('students', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Студенты курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удален')),
            ],
            options={
                'verbose_name': 'Вопрос - ответ',
                'verbose_name_plural': 'Вопросы - ответы',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=50, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Талант')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удален')),
            ],
            options={
                'verbose_name': 'Талант',
                'verbose_name_plural': 'Таланты',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Videolesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='Название видеоурока')),
                ('description', models.TextField(blank=True, verbose_name='Описание видеоурока')),
                ('path_to_file', models.FilePathField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('viewed', models.BooleanField(default=False, verbose_name='Просмотрен')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.course')),
            ],
            options={
                'verbose_name': 'Видеоурок',
                'verbose_name_plural': 'Видеоуроки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentsWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Работа студента',
                'verbose_name_plural': 'Работы студентов',
            },
        ),
        migrations.CreateModel(
            name='Onlinelesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='Название онлайн-урока')),
                ('link', models.CharField(max_length=150, verbose_name='Ссылка на онлайн-урок')),
                ('lesson_date', models.DateTimeField(verbose_name='Дата онлайн-урока')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.course')),
                ('students', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Онлайн урок',
                'verbose_name_plural': 'Онлайн уроки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя ментора')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия ментора')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото ментора')),
                ('courses', models.ManyToManyField(to='mainapp.course', verbose_name='')),
            ],
            options={
                'verbose_name': 'Ментор',
                'verbose_name_plural': 'Менторы',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(to='mainapp.tag', verbose_name='Теги курса'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('approved', models.BooleanField(default=False, verbose_name='Заявка подтверждена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.course')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['created_at'],
            },
        ),
    ]
