# Generated by Django 4.2.5 on 2023-10-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='benefits',
            field=models.ManyToManyField(to='mainapp.benefit', verbose_name='Польза курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='talents',
            field=models.ManyToManyField(to='mainapp.talent', verbose_name='Навыки, которые дает курс'),
        ),
    ]
