# Generated by Django 4.2.5 on 2023-10-15 09:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_course_benefits_course_talents'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=50, verbose_name='Промокод')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('expiration_date', models.DateTimeField(verbose_name='Действует до')),
            ],
        ),
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=models.CharField(max_length=50, verbose_name='Текст тега'),
        ),
    ]
