# Generated by Django 4.2.5 on 2023-10-15 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_promocode_alter_tag_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'ordering': ['-created_at'], 'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
    ]
