# Generated by Django 4.2.5 on 2023-10-15 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0004_alter_promocode_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='mainapp.course'),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='application',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='benefits',
            field=models.ManyToManyField(related_name='courses', to='mainapp.benefit', verbose_name='Польза курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Студенты курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(related_name='courses', to='mainapp.tag', verbose_name='Теги курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='talents',
            field=models.ManyToManyField(related_name='courses', to='mainapp.talent', verbose_name='Навыки, которые дает курс'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='courses',
            field=models.ManyToManyField(related_name='mentors', to='mainapp.course', verbose_name='Курсы'),
        ),
        migrations.AlterField(
            model_name='onlinelesson',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onlinelessons', to='mainapp.course'),
        ),
        migrations.AlterField(
            model_name='onlinelesson',
            name='link',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ссылка на онлайн-урок'),
        ),
        migrations.AlterField(
            model_name='onlinelesson',
            name='students',
            field=models.ManyToManyField(related_name='onlinelessons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentswork',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentworks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videolessons', to='mainapp.course'),
        ),
    ]
