# Generated by Django 4.2.5 on 2023-10-15 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_application_course_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='onlinelesson',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='studentswork',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='videolesson',
            old_name='course_id',
            new_name='course',
        ),
    ]
