# Generated by Django 4.2.5 on 2023-10-19 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_rename_course_id_application_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='some_str', max_length=200, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlinelesson',
            name='slug',
            field=models.SlugField(default='some_str', max_length=200, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.course'),
        ),
        migrations.AddField(
            model_name='videolesson',
            name='slug',
            field=models.SlugField(default='some_str', max_length=200, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('ART', 'ИСКУССТВО'), ('DESIGN', 'ДИЗАЙН'), ('SOFT_SKILLS', 'SOFT SKILLS')], max_length=11, verbose_name='Категория курса'),
        ),
        migrations.AlterField(
            model_name='studentswork',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
    ]
