# Generated by Django 4.2.5 on 2023-10-22 16:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0008_course_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='students',
            field=models.ManyToManyField(related_name='promocodes', to=settings.AUTH_USER_MODEL),
        ),
    ]
