# Generated by Django 4.2.5 on 2023-10-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_promocode_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='сourses_images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teaser_video',
            field=models.FilePathField(blank=True, null=True, path='/home/teamwork/2210/ProjectP/app/media/teaser_video', verbose_name='Тизер-видео'),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='path_to_file',
            field=models.FilePathField(path='/home/teamwork/2210/ProjectP/app/media/lessons_videos'),
        ),
    ]
