# Generated by Django 4.2.5 on 2023-10-25 19:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_remove_course_category_alter_course_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preparation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=50, verbose_name='Значение')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='age_group',
            field=models.CharField(blank=True, max_length=15, verbose_name='Возрастная группа'),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, max_length=15, verbose_name='Продолжительность курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='lesson_qty',
            field=models.CharField(blank=True, max_length=15, verbose_name='Количество уроков'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teaser_video',
            field=models.FilePathField(blank=True, null=True, path='/Users/Macintosh/Desktop/ProjectP/app/media/teaser_video', verbose_name='Тизер-видео'),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='path_to_file',
            field=models.FilePathField(path='/Users/Macintosh/Desktop/ProjectP/app/media/video_lessons'),
        ),
    ]
