# Generated by Django 4.2.5 on 2023-10-26 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_preparation_course_age_group_course_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='preparation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.preparation'),
        ),
    ]
