# Generated by Django 4.2.5 on 2023-10-27 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_subscribers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribers',
            new_name='Subscriber',
        ),
    ]
