# Generated by Django 4.2.5 on 2023-10-27 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_rename_subscribers_subscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ['first_name', 'email'], 'verbose_name': 'Подписчик на новостную рассылку', 'verbose_name_plural': 'Подписчики на новостную рассылку'},
        ),
    ]
