# Generated by Django 4.2.5 on 2023-10-28 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_preparation_options_alter_course_age_group_and_more'),
        ('mainapp', '0014_alter_subscriber_options'),
    ]

    operations = [
    ]
