# Generated by Django 4.2.5 on 2023-10-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_merge_20231028_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='approach',
            field=models.TextField(default='Подход в обучении', verbose_name='Подход в обучении'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='credo',
            field=models.TextField(default='Кредо и сильные стороны', verbose_name='Кредо и Сильные стороны'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='experience',
            field=models.TextField(default='Образование и опыт', verbose_name='Образование и Опыт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='status',
            field=models.CharField(default='Статус', max_length=255, verbose_name='Статус'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='teaser_video',
            field=models.FilePathField(blank=True, null=True, path='C:\\Users\\perev\\Downloads\\ProjectP\\app\\media\\teaser_video', verbose_name='Тизер-видео'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='mentor', verbose_name='Фото ментора'),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='path_to_file',
            field=models.FilePathField(path='/media/lessons_videos'),
        ),
    ]
