# Generated by Django 4.2.5 on 2023-10-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_mentor_approach_mentor_credo_mentor_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teaser_video',
            field=models.FilePathField(blank=True, null=True, path='/home/teamwork/2810/ProjectP/app/media/teaser_video', verbose_name='Тизер-видео'),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='path_to_file',
            field=models.FilePathField(path='/home/teamwork/2810/ProjectP/app/media/lessons_videos'),
        ),
    ]
