# Generated by Django 4.2.5 on 2023-10-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_alter_benefit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='filling',
            field=models.TextField(blank=True, verbose_name='Наполнение курса'),
        ),
    ]
