# Generated by Django 4.2.5 on 2023-10-29 17:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_alter_talent_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='Название урока')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lessons_img/', verbose_name='Изображение')),
                ('сourses', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.course')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['сourses'],
            },
        ),
    ]
