# Generated by Django 4.2.5 on 2023-10-29 18:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='Название урока')),
                ('number', models.IntegerField(verbose_name='Номер урока')),
                ('part1', models.CharField(max_length=150, verbose_name='Название первой части описания урока')),
                ('part1_description', models.TextField(blank=True, verbose_name='Содержание первой части')),
                ('part2', models.CharField(max_length=150, verbose_name='Название второй части описания урока')),
                ('part2_description', models.TextField(blank=True, verbose_name='Содержание второй части')),
                ('part3', models.CharField(max_length=150, verbose_name='Название третьей части описания урока')),
                ('part3_description', models.TextField(blank=True, verbose_name='Содержание третьей части')),
                ('part4', models.CharField(max_length=150, verbose_name='Название четвёртой части описания урока')),
                ('part4_description', models.TextField(blank=True, verbose_name='Содержание четвёртой части')),
                ('part5', models.CharField(max_length=150, verbose_name='Название пятой части описания урока')),
                ('part5_description', models.TextField(blank=True, verbose_name='Содержание пятой части')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lessons_img/', verbose_name='Изображение')),
                ('сourses', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.course')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['сourses'],
            },
        ),
        migrations.DeleteModel(
            name='Education',
        ),
    ]
