# Generated by Django 4.2.5 on 2023-10-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_lessons_delete_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='part1',
            field=models.CharField(blank=True, max_length=150, verbose_name='Название первой части описания урока'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='part2',
            field=models.CharField(blank=True, max_length=150, verbose_name='Название второй части описания урока'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='part3',
            field=models.CharField(blank=True, max_length=150, verbose_name='Название третьей части описания урока'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='part4',
            field=models.CharField(blank=True, max_length=150, verbose_name='Название четвёртой части описания урока'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='part5',
            field=models.CharField(blank=True, max_length=150, verbose_name='Название пятой части описания урока'),
        ),
    ]
