# Generated by Django 4.2.5 on 2023-11-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_alter_lessons_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='description_part4',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='description_part5',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='part4',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='part5',
        ),
        migrations.AlterField(
            model_name='course',
            name='teaser_video',
            field=models.FilePathField(blank=True, null=True, path='/home/teamwork/0111/ProjectP/app/media/teaser_video', verbose_name='Тизер-видео'),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='path_to_file',
            field=models.FilePathField(path='/home/teamwork/0111/ProjectP/app/media/video_lessons'),
        ),
    ]
