# Generated by Django 4.2.5 on 2023-11-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_remove_lessons_description_part4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='part1',
            field=models.CharField(blank=True, default='Цель урока', max_length=150, verbose_name='Название первой части описания урока'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='part2',
            field=models.CharField(blank=True, default='Чему научится ребенок?', max_length=150, verbose_name='Название второй части описания урока'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='part3',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Название третьей части описания урока'),
        ),
    ]
