# Generated by Django 4.2.5 on 2023-11-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_alter_lessons_part1_alter_lessons_part2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='part3',
            field=models.CharField(blank=True, default='Что нужно для урока?', max_length=150, verbose_name='Название третьей части описания урока'),
        ),
    ]
