# Generated by Django 4.2.5 on 2023-11-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_alter_course_teaser_video_alter_lesson_path_to_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='quote',
            field=models.TextField(default='Детские рисунки похожи на петроглифы - самое первое изобразительное искусство человека. Твои рисунки - это то, чем вдохновляются даже самые великие художники.', verbose_name='Высказывание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promocode',
            name='discount',
            field=models.IntegerField(default=500, verbose_name='Сумма скидки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promocode',
            name='subscribers',
            field=models.ManyToManyField(related_name='promocodes', to='mainapp.subscriber'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teaser_video',
            field=models.FilePathField(blank=True, null=True, path='C:\\Users\\perev\\Downloads\\ProjectP\\app\\media\\teaser_video', verbose_name='Тизер-видео'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='path_to_file',
            field=models.FilePathField(blank=True, path='C:\\Users\\perev\\Downloads\\ProjectP\\app\\media\\video_lessons'),
        ),
    ]
