# Generated by Django 4.2.5 on 2023-11-02 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_mentor_quote_promocode_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='note',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='viewed',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='students',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='course',
            name='aim',
            field=models.CharField(blank=True, max_length=200, verbose_name='Цель курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='mentors',
            field=models.ManyToManyField(related_name='courses', to='mainapp.mentor', verbose_name='Менторы'),
        ),
        migrations.AddField(
            model_name='course',
            name='question_access_duration',
            field=models.TextField(default='', verbose_name='На сколько по времени доступен курс?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='question_hometask',
            field=models.TextField(default='', verbose_name='Что насчет домашнего задания?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='question_joining_telegram_chat',
            field=models.TextField(default='', verbose_name='Что я получу, вступив в телеграм-канал курса?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='question_lessons_features',
            field=models.TextField(default='', verbose_name='Как проходят занятия на курсе?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='question_paid_no_access',
            field=models.TextField(default='', verbose_name='Я оплатил и не получил доступ к курсу'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promocode',
            name='for_students',
            field=models.BooleanField(default=False, verbose_name='Для зарегистрированных пользователей'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promocode',
            name='for_subscribers',
            field=models.BooleanField(default=False, verbose_name='Для подписчиков на новости'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='preparation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='mainapp.preparation'),
        ),
        migrations.DeleteModel(
            name='QuestionAnswer',
        ),
    ]
