# Generated by Django 4.2.5 on 2023-11-02 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0036_remove_course_note_remove_lesson_viewed_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advantage',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='question_hometask',
            new_name='question_homework',
        ),
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.AlterField(
            model_name='application',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='mainapp.course', verbose_name='Курсы'),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='course',
            name='preparation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='mainapp.preparation', verbose_name='Уровень подготовки'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='mainapp.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='studentswork',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentworks', to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
    ]
