# Generated by Django 4.2.5 on 2023-11-02 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_delete_advantage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='aim',
            new_name='note',
        ),
    ]
