# Generated by Django 4.2.5 on 2023-11-04 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0038_rename_aim_course_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teaser_video',
            field=models.FilePathField(blank=True, null=True, path='D:\\Study\\Python\\04_Quart\\03_Командная разработка по методологии Agile SCRUM (практика)\\git\\ProjectP\\app\\media\\teaser_video', verbose_name='Тизер-видео'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='path_to_file',
            field=models.FilePathField(blank=True, path='D:\\Study\\Python\\04_Quart\\03_Командная разработка по методологии Agile SCRUM (практика)\\git\\ProjectP\\app\\media\\video_lessons'),
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('lesson_number', models.IntegerField(default=1, verbose_name='Номер доступного урока')),
                ('note', models.TextField(null=True, verbose_name='Примечания по студенту на этом курсе')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='mainapp.course', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Курс студента',
                'verbose_name_plural': 'Курс студента',
                'ordering': ['-created_at'],
            },
        ),
    ]
