# Generated by Django 4.2.5 on 2023-11-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0039_alter_course_teaser_video_alter_lesson_path_to_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='description_part1',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='description_part2',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='description_part3',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='part1',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='part2',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='part3',
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание урока'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_goal',
            field=models.TextField(blank=True, verbose_name='Цель урока'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='materials',
            field=models.TextField(blank=True, verbose_name='Что нужно для урока'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='new_skill',
            field=models.TextField(blank=True, verbose_name='Чему научится ребенок'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teaser_video',
            field=models.FilePathField(blank=True, null=True, path='C:\\Users\\perev\\Downloads\\ProjectP\\app\\media\\teaser_video', verbose_name='Тизер-видео'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='path_to_file',
            field=models.FilePathField(blank=True, path='/media/lessons_videos'),
        ),
    ]
