# Generated by Django 4.2.5 on 2023-11-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0040_remove_lesson_description_part1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='path_to_file',
        ),
        migrations.AddField(
            model_name='lesson',
            name='path_to_pdf_file',
            field=models.FilePathField(blank=True, path='C:\\Users\\perev\\Downloads\\ProjectP\\app\\media\\lessons/files'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='path_to_video_file',
            field=models.FilePathField(blank=True, path='C:\\Users\\perev\\Downloads\\ProjectP\\app\\media\\lessons/videos'),
        ),
    ]
