# Generated by Django 4.2.5 on 2023-11-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0041_remove_lesson_path_to_file_lesson_path_to_pdf_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='path_to_pdf_file',
            field=models.FilePathField(blank=True, path='/media/lessons_videos/files'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='path_to_video_file',
            field=models.FilePathField(blank=True, path='/media/lessons_videos/videos'),
        ),
    ]
