# Generated by Django 4.2.5 on 2023-11-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0043_alter_lesson_path_to_pdf_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='path_to_pdf_file',
            field=models.FilePathField(blank=True, path='C:\\Users\\perev\\Downloads\\ProjectP\\app\\media\\lessons_files', verbose_name='Дополнительный файл'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='path_to_video_file',
            field=models.FilePathField(blank=True, path='C:\\Users\\perev\\Downloads\\ProjectP\\app\\media\\lessons_videos', verbose_name='Видео в записи'),
        ),
    ]
