# Generated by Django 4.2.5 on 2023-11-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0044_alter_lesson_path_to_pdf_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teaser_video',
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(verbose_name='Стоимость курса'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='path_to_pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='lessons_files/', verbose_name='Дополнительный файл'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='path_to_video_file',
            field=models.FileField(blank=True, null=True, upload_to='lessons_videos/', verbose_name='Видео в записи'),
        ),
    ]
