# Generated by Django 4.2.5 on 2023-11-05 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0045_remove_course_teaser_video_alter_course_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
