# Generated by Django 4.2.5 on 2023-11-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0046_remove_course_tags_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='telegram_channel_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на тг-канал'),
        ),
    ]
