# Generated by Django 4.2.5 on 2023-11-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0047_course_telegram_channel_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='path_to_pdf_file',
            new_name='pdf_file',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='path_to_video_file',
            new_name='video_file',
        ),
        migrations.AddField(
            model_name='promocode',
            name='for_user',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Промокод для конкретного юзера (указать email)'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount',
            field=models.IntegerField(verbose_name='Скидка в %'),
        ),
    ]
