# Generated by Django 4.2.5 on 2023-11-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0048_rename_path_to_pdf_file_lesson_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='purchase_price',
            field=models.IntegerField(default=500, verbose_name='Цена покупки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promocode',
            name='text',
            field=models.CharField(max_length=50, unique=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='note',
            field=models.TextField(blank=True, default='a', verbose_name='Примечания по студенту на этом курсе'),
            preserve_default=False,
        ),
    ]
