# Generated by Django 4.2.5 on 2023-11-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0049_studentcourse_purchase_price_alter_promocode_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
    ]
