# Generated by Django 4.2.5 on 2023-11-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0050_promocode_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='purchase_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена покупки'),
        ),
    ]
