# Generated by Django 4.2.5 on 2023-11-10 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0053_alter_studentshomework_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentshomework',
            name='student',
            field=models.ForeignKey(default='86073d7d-cb51-48c3-92c0-d7161639d97d', on_delete=django.db.models.deletion.CASCADE, related_name='studenthomework', to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
            preserve_default=False,
        ),
    ]
