# Generated by Django 4.2.5 on 2023-11-10 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0054_studentshomework_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentshomework',
            name='description',
        ),
    ]
