# Generated by Django 4.2.5 on 2023-11-14 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0055_remove_studentshomework_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lesson_qty',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
