# Generated by Django 4.2.5 on 2023-11-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0056_remove_course_lesson_qty_delete_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='on_sale',
            field=models.BooleanField(default=False, verbose_name='В продаже'),
        ),
    ]
