# Generated by Django 4.2.5 on 2023-11-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0057_course_on_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='bank',
            field=models.CharField(blank=True, max_length=150, verbose_name='Банк'),
        ),
    ]
